### ISSUE TITLE
Possible limitation/bug: event handlers not perserved

### ISSUE THREAD

**Issue by ksk100** [Tipue/Popr#1]
If you create a menu, and then attach some complex event handlers to the A elements in the HTML used to generate the menu, then these are lost in the process of menu creation.

I think this is because Popr works by recreating the menu's HTML by calling jQuery's `html()`, which I think is obliterating any attached handlers.

This means that Popr doesn't work very well, for example, with Knockout.

**Comment by Tipue** [comment]
It does use `html()`. I'll look into doing this a different way in the next release.

**Comment by ksk100** [comment]
Excellent, thank you.
