### ISSUE TITLE
Automatic positioning on screen edges

### ISSUE THREAD

**Issue by peucaio** [Tipue/Popr#2]
I chose Popr to use as the popup script for an e-commerce website, but I couldn't use it for a simple task: the typical "My Account" and "My Cart" buttons located on the website top-right position.

![screen shot 2016-04-11 at 6 29 39 pm](https://cloud.githubusercontent.com/assets/292803/14443090/820a7508-0013-11e6-8a27-77991ca5b056.png)

I've changed the .ico-cart .popr_container_bottom width to 200px, to better fit the elements inside the popup. But the popup stays outside the screen, as you can see above. Am I doing something wrong defining this width, or should the script automatically detect the x position and "fit" inside the screen?

Thanks.

**Comment by Tipue** [comment]
Sorry, it's a simple popup by design and doesn't detect where it appears. I'll look to improve this in the next release.

**Comment by peucaio** [comment]
Ok, thanks!
