### ISSUE TITLE
problems on Mozilla Firefox 46.0.1

### ISSUE THREAD

**Issue by sbraaa** [Tipue/Popr#3]
Using Popr on firefox raise up a very strange behaviour: on firefox styles are ignored (no hover) and user cannot select options from popr box. If exists a link under popr box it will be fired as if popr were invisibile!
The same code, flushing any cache, runs very well in other browsers (IE, Chrome, Safari on linux/win/mac).

**Comment by sbraaa** [comment]
Ok, problem depends on using button tag, using div it runs as expected.
(very strange that other browser don't have this kind of behaviour!)

**Comment by sbraaa** [comment]
Ok, problem depends on using button tag, using div it runs as expected.
(very strange that other browser don't have this kind of behaviour!)

**Comment by Tipue** [comment]
No problem. :-)
